### ISSUE TITLE
Installed with no issues, but doesn't work

### ISSUE THREAD

**Issue by trapchik** [Itonomy/magento2-bundle-products-change-qty#4]
How to check the module has been installed?
Cache has been updated (php bin/magento c:f)
Magento 2.2.6

Thanks

**Comment by RaphaelBronsveld** [comment]
Hi @trapchik ,

Did you run `php bin/magento setup:upgrade` ? Make sure the `'Itonomy_BundleProductChangeQty' => 1` exists in app/etc/config.php.

When enabled, the bundle products (with checkbox based options), should now show quantity fields. This only happens when you have not overwritten the checkbox template yourself (block `product.info.bundle.options.checkbox` is being overwritten with a different template).

Let me know if this works for you!

**Comment by trapchik** [comment]
@RaphaelBronsveld Please could you confirm the directory I need to put your model files in? as I have done the above steps with no success

**Comment by RaphaelBronsveld** [comment]
Hi @trapchik , I'm not sure what you mean by that.

The files are already in the correct place when you installed this with composer.
Enabling the module is the only thing that needs to happen afterwards, if this doesn't work, it's probably because the code on your end also overwrites the Type model or the template in my previous comment.

**Comment by trapchik** [comment]
sorry @RaphaelBronsveld 
looks like was some permissions issue
all good now

may we ask, why you did not consider to remove default "1 x" text and put quantity text field instead?

thanks

**Comment by RaphaelBronsveld** [comment]
Hi @trapchik ,

Happy to help!
This is done because I wanted it to be as close to Magento's core as possible. 
Any further template changes can be based on this module's template.
